@startuml
!include ../C4_Container.puml
!include ../level_1_system_context/person/persons.puml
!include ../level_1_system_context/database/databases.puml
!include ./container/containers.puml

title Container diagram for Financial System

humanResourcesPerson()
databaseSystem()

Boundary(financialSystemBoundary, "Financial System", "System") {
    webApplicationContainer()
    apiApplicationContainer()
}

Rel_D(humanResources, webApplication, "Add, view and manipulate employees using", "HTTP")
Rel_D(humanResources, apiApplication, "Add, view and manipulate employees using", "JSON/HTTP")

Rel_D(webApplication, database, "Reads and writes employee information", "JDBC")
Rel_D(apiApplication, database, "Reads and writes employee information", "JDBC")

@enduml