@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml

!function databaseSystem()
    SystemDb(database, "Database", "Stores information about employees.")
!endfunction

@enduml