@startuml
!include ../../C4_Container.puml

!procedure webApplicationContainer()
    Container(webApplication, "Web Application", "Java, Spring", "Provides internet functionality to human resources for managing employees via web browser.")
!endprocedure

!procedure apiApplicationContainer()
    Container(apiApplication, "API Application", "Java, Ratpack", "Provides internet functionality to human resources for managing employees via JSON/HTTP API.")
!endprocedure

@enduml