@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml
!include ../level_1_system_context/person/persons.puml
!include ../level_1_system_context/database/databases.puml
!include ../level_2_container/container/containers.puml

title Component Diagram for Financial System

humanResourcesPerson()

Boundary(infrastructureLayer, "infrastructure", "Layer") {
    databaseSystem()
}

Boundary(webApplicationContainerBoundary, "Web Application", "Container") {
    Boundary(presentationLayer, "presentation", "Layer") {
        Component(springComponent, "spring", "Spring", "Allows user to interact with system via web page.")
        Component(springTemplates, "templates", "HTML", "Templates for web application.")
    }

    Boundary(applicationLayer, "application", "Layer") {
        Component(financialSystem, "application", "Java", "Application business rules. \nFinancial system use cases.")
    }

    Boundary(domainLayer, "domain", "Layer") {
        Component(employee, "employee", "Java", "Employees entities.")
        Component(exceptions, "exceptions", "Java", "Financial system exceptions.")
        Component(ports, "ports", "Java", "Ports interfaces.")
        Component(salary, "salary", "Java", "Business rules for calculating salaries.")

    }
}
Rel(financialSystem, employee, "Uses")
Rel(financialSystem, exceptions, "Uses")
Rel(financialSystem, ports, "Uses")
Rel(financialSystem, salary, "Uses")

Rel(humanResources, springComponent, "Makes API calls to", "JSON/HTTP")
Rel(springComponent, financialSystem, "Uses", "Java")
Rel_L(springComponent, springTemplates, "Uses")
Rel(ports, database, "Reads and writes employee information", "JDBC")
@enduml
