@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml
!include ./person/persons.puml
!include ./database/databases.puml

title System Context Diagram for Financial System

humanResourcesPerson()
databaseSystem()

System(financialSystem, "Financial System", "System for managing employees. \nProvides multiple operations on employees. \n(e.g. \nAdd new employee. \nGive rise to employee. \nEtc.)")

Rel_D(humanResources, financialSystem, "Add, view and manipulate employees using")
Rel_D(financialSystem, database, "Reads and writes employees data from and to")
@enduml
